spring:
  datasource:
    url: jdbc:mariadb://correct-ing.cqfifksuvrnp.ap-northeast-2.rds.amazonaws.com:3306/correcting?serverTimezone=Asia/Seoul&useLegacyDatetimeCode=false&rewriteBatchedStatements=true
    username: admin
    password: admin11!
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximumPoolSize: 100
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        jdbc:
          batch_size: 1000
    open-in-view: false

springdoc:
  packages-to-scan: com.mju.correcting
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: demo-ui.html            # Swagger UI ?? => localhost:8000/demo-ui.html
    tags-sorter: alpha            # alpha: ??? ? ?? ??, method: HTTP Method ? ??
    operations-sorter: alpha      # alpha: ??? ? ?? ??, method: HTTP Method ? ??
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
  cache:
    disabled: true

jwt:
  secret: 9cbb3605dd40d39e01f1dasdb071a160b41c6a5fa4f1c0ef665821545435b28a0159bd6f446d45fe9d58732b93abc2ff73f152b1cfba04f3ecb5549206c79922